Controllers/AdminLayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AcunMedyaPortfolioProject.Controllers
{
    public class AdminLayoutController : Controller
    {
        // GET: AdminLayout
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult PartialHead()
        {
            return PartialView();
        }
        public PartialViewResult PartialSidebar()
        {
            return PartialView();
        }
        public PartialViewResult PartialScripts()
        {
            return PartialView();
        }
    }
}

Views/AdminLayout/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<!doctype html>
<html lang="en">
@Html.Action("PartialHead", "AdminLayout") 
<body>

    <div class="wrapper d-flex align-items-stretch">
        @Html.Action("PartialSidebar", "AdminLayout")

        <!-- Page Content  -->
        <div id="content" class="p-4 p-md-5">


            @RenderBody()

        </div>
    </div>
    @Html.Action("PartialScripts","AdminLayout")
  
</body>
</html>

Views/AdminLayout/PartialHead.cshtml
<head>
    <title>Sidebar 01</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/sidebar-01/css/style.css">
</head>

Views/AdminLayout/PartialScripts.cshtml
<script src="~/sidebar-01js/jquery.min.js"></script>
<script src="~/sidebar-01js/popper.js"></script>
<script src="~/sidebar-01js/bootstrap.min.js"></script>
<script src="~/sidebar-01js/main.js"></script>

Views/AdminLayout/PartialSidebar.cshtml
<nav id="sidebar">
    <div class="p-4 pt-5">
        <a href="#" class="img logo rounded-circle mb-5" style="background-image: url(/sidebar-01images/logo.jpg);"></a>
        <ul class="list-unstyled components mb-5">

            <li>
                <a href="#">Hakkımda</a>
            </li>

            <li>
                <a href="#">Kategoriler</a>
            </li>
            <li>
                <a href="#">İletişim</a>
            </li>
            <li>
                <a href="#">Eğitim</a>
            </li>
            <li>
                <a href="#">Deneyim</a>
            </li>
            <li>
                <a href="#">Tanıtım</a>
            </li>
            <li>
                <a href="#">proje</a>
            </li>
            <li>
                <a href="#">Yorumlar</a>
            </li>
        </ul>

        <div class="footer">
            <p>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                telif hakkı &copy;
                <script>document.write(new Date().getFullYear());</script> Tüm hakları saklıdır.
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
        </div>

    </div>
</nav>